# typed: false
# frozen_string_literal: true

# Homebrew formula for agentctl — generated by scripts/gen_formula.py.
# Do not hand-edit; the release workflow regenerates + pushes this.
class Agentctl < Formula
  desc "Manage containerized coding-agent CLIs (Claude, Codex, Gemini) — front half of a Control Plane harness"
  homepage "https://github.com/rxdn-forge/agentctl-dist"
  url "https://github.com/rxdn-forge/agentctl-dist/releases/download/v0.6.36/agentctl-0.6.36-py3-none-any.whl", using: :nounzip
  sha256 "0e2965c3cd190efd7ab5e395acdb1a6b1f594213afe8e5756fd615b22098961b"
  license "MIT"

  depends_on "python@3.11"

  def install
    venv = virtualenv_create(libexec, "python3.11")
    # cached_download is the sha256-verified wheel; pip resolves runtime deps
    # from PyPI. (No `resource` stanzas needed — and none would be honored for
    # a wheel install.)
    system libexec/"bin/pip", "install", "--no-cache-dir", cached_download
    bin.install_symlink libexec/"bin/agentctl"
  end

  test do
    assert_match "0.6.36", shell_output("#{bin}/agentctl --version")
  end
end
