# typed: false
# frozen_string_literal: true

# Homebrew formula for agentctl — generated by scripts/gen_formula.py.
# Do not hand-edit; the release workflow regenerates + pushes this.
class Agentctl < Formula
  desc "Manage containerized coding-agent CLIs for a Control Plane harness"
  homepage "https://github.com/rxdn-forge/agentctl-dist"
  url "https://github.com/rxdn-forge/agentctl-dist/releases/download/v0.6.123/agentctl-0.6.123-py3-none-any.whl", using: :nounzip
  sha256 "7723fb3526c06e2833e0d9f94875af2dc3bbf387c0e7d6b48bb61ac4deeb1098"
  license "MIT"

  depends_on "python@3.11"

  def install
    virtualenv_create(libexec, "python3.11")
    # cached_download is the sha256-verified wheel; pip resolves runtime deps
    # from PyPI. (No `resource` stanzas needed — and none would be honored for
    # a wheel install.)
    system libexec/"bin/pip", "install", "--no-cache-dir", cached_download
    bin.install_symlink libexec/"bin/agentctl"
    bin.install_symlink libexec/"bin/actl"
  end

  test do
    assert_match "0.6.123", shell_output("#{bin}/agentctl --version")
    assert_match "0.6.123", shell_output("#{bin}/actl --version")
    assert_match "Ed25519", shell_output("#{bin}/agentctl signing runtime")
  end
end
