# typed: false
# frozen_string_literal: true

# Homebrew formula for agentctl — generated by scripts/gen_formula.py.
# Do not hand-edit; the release workflow regenerates + pushes this.
class Agentctl < Formula
  desc "Manage containerized coding-agent CLIs (Claude, Codex, Gemini) — front half of a Control Plane harness"
  homepage "https://github.com/rxdn-forge/agentctl-dist"
  url "https://github.com/rxdn-forge/agentctl-dist/releases/download/v0.6.74/agentctl-0.6.74-py3-none-any.whl", using: :nounzip
  sha256 "88003f478b1d7854e50b6a1e11305d78517c7caacd2f575e117dd35366ecd6d2"
  license "MIT"

  depends_on "python@3.11"

  def install
    venv = virtualenv_create(libexec, "python3.11")
    # cached_download is the sha256-verified wheel; pip resolves runtime deps
    # from PyPI. (No `resource` stanzas needed — and none would be honored for
    # a wheel install.)
    system libexec/"bin/pip", "install", "--no-cache-dir", cached_download
    bin.install_symlink libexec/"bin/agentctl"
    bin.install_symlink libexec/"bin/actl"
  end

  test do
    assert_match "0.6.74", shell_output("#{bin}/agentctl --version")
    assert_match "0.6.74", shell_output("#{bin}/actl --version")
    assert_match "Ed25519", shell_output("#{bin}/agentctl signing runtime")
  end
end
